# Adapted from https://github.com/numba/numba/blob/master/azure-pipelines.yml
trigger:
- master
- 1.1.x

pr:
- master
- 1.1.x

variables:
  PYTEST_WORKERS: auto

jobs:
# Mac and Linux use the same template
- template: ci/azure/posix.yml
  parameters:
    name: macOS
    vmImage: macOS-10.14

- template: ci/azure/posix.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/azure/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
