language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.6

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- travis_retry conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- travis_retry pip install tf-nightly numpy scipy h5py pytest flaky pandas --progress-bar off
- travis_retry conda install -q pydot graphviz Pillow


install:
- python setup.py install

script:
- pytest tests/ --ignore=tests/docs --ignore=tests/keras/legacy/layers_test.py --ignore=tests/test_api.py
